### PR TITLE
Implement optional Serde 1.0 support

### PR DESCRIPTION
**Pull request by xfix**
Note that this is not ready for merging, as it doesn't run Travis tests. I'm not sure what should be testing strategy?

### CODE REVIEW

**Comment by bluss** [comment]
One can use a private crate in the repo with extra tests if one wants to split out those tests and their dependencies.

Thanks for working on this.

I kind of want to say that we need to support both kinds of serialization with serde (the kind that gets context from the stream [JSON] and the bon-self-describing kind [bincode]). Unfortunately I'm not 100% sure how to ensure compat with both.

**Comment by xfix** [comment]
This I'm fairly sure should support both JSON and bincode. All the serialization method does is telling that this is a hash map, and its size (for formats that require size in advance, like bincode). The deserialization method is really simple, it just deserializes a map with size that may or may not be specified by a format (JSON doesn't specify map size, bincode does).

The test function tests if this can be successfully serialized and deserialized.

**Comment by LegNeato** [comment]
Any chance on getting this merged soon?

**Comment by bluss** [comment]
Sure. I'm sorry that it fell of my to do list. Friendly pings are good.

**Comment by bluss** [comment]
I'm fixing up .travis.yml

**Comment by bluss** [comment]
In 0.2.11

**Comment by LegNeato** [comment]
Wow, thanks for the quick turnaround on the merging and release!

**Pull request merged**
