### PR TITLE
Link the README.md file in Cargo.toml

### PR DESCRIPTION
**Pull request by notriddle**
This way, crates.io and docs.rs will render it.

### CODE REVIEW

**Comment by bluss** [comment]
I'm sorry, there is no README.md file :smile:

**Comment by notriddle** [comment]
Oh, oops.

...

I guess if I set `readme = "README.rst"`, crates.io will try to render the ReStructuredText as Markdown? @anthonynguyen

**Comment by bluss** [comment]
Yes. It doesn't look entirely terrible but it's not so good.

**Comment by bluss** [comment]
Oh we have an example from ndarray 0.10.4 before I removed the readme key. For it, the rst as markdown looks especially bad

https://crates.io/crates/ndarray/0.10.4

**Comment by notriddle** [comment]
:-1: nope 😞

**Comment by bluss** [comment]
Thanks anyway! I'm impressed by the diligence of the rust community, so many people were ready with their readme keys long before it had any use.

**Pull request closed without merging**
